#!/bin/bash -l
#SBATCH --account=bcamley1
#SBATCH --job-name=tau_table
#SBATCH --time=24:0:0
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=shared
#SBATCH --array=1,2,3,4,5,6,7,8

python -u generate_tau_table.py ${SLURM_ARRAY_TASK_ID}
